### ISSUE TITLE
[Other] Paperless Organization Organization

### ISSUE THREAD

**Issue by qcasey** [jonaswinkler/paperless-ng#1632]
As seems commonly agreed in #1599, a new Github Organization should be build around this project. Can those willing to do the work of migrating to a GitHub organization for paperless-ng chime in here?

## Currently created Paperless Organizations

_Ordered by stars_

1. paperless-ngx [repo](https://github.com/paperless-ngx/paperless-ng) [people](https://github.com/orgs/paperless-ngx/people)
2. paperless-reborn [repo](https://github.com/paperless-reborn/paperless-ng) [people](https://github.com/orgs/paperless-reborn/people)

@FrankStrieter, can you confirm you're willing to invite members to paperless-ngx, and who you've invited so far?

I do not know who created paperless-reborn

## Tasks (unconfirmed)

- [ ] Invite any willing [paperless-ng contributors](https://github.com/jonaswinkler/paperless-ng/graphs/contributors) to the organization, as they are most familiar with the codebase.
- [ ] Bring on willing new contributors with experience in
  1. Python
  2. Angular
  3. Project Leadership
- [ ] Migrate issues (?)
- [ ] Merge [pending PRs](https://github.com/jonaswinkler/paperless-ng/pulls)

## Willing Contributors

- @qcasey I can help in organizing this transition, unless anyone else wants to handle. I contribute to the android apps [paperless_app](https://github.com/bauerj/paperless_app) and [paperless_share](https://github.com/qcasey/paperless_share).

IMO, @jonaswinkler @danielquinn and @shamoon should have write access to this org, as they've all made significant contributions to the paperless project. No one should expect any help from them now, but if they want to contribute in the future it should be made easy.

**Comment by a17t** [comment]
Thanks @qcasey .

As for myself, in the past I have been a user of the original paperless and recently paperless-ng.

I have some professional experience in python and angular, although those never were my focus areas. Same goes for a project organisation, which goes along with work in consulting and software projects.

I'd be happy to participate, although I have be clear, that I only have limited time available.

**Comment by isigmund** [comment]
I would also like to contribute as my time permits. I have some experience in python backend development using Django and Flask within other open source projects.

I also could help out with some of the project management tasks, since I am working as a Product Owner for Scrum based software development projects in my daytime job....

**Comment by schirinowski** [comment]
I could bring in translation skills (English <> German) from time to time and am willing to test things.

Would be happy to contribute to seeing Paperless survive and develop for a looong, looong time!

**Comment by gador** [comment]
I'd also like to help. I use paperless-ng for my private and work related paper management.
I can help with Python development, testing and potentially packaging (at least for NixOS and Docker). Also, like @umoenks I can help with German translation.

**Comment by a17t** [comment]
A lot of Germans here. (Me too)


Sorry had to leave that sidenote. Seems that Germany is the land of paperwork

**Comment by sytone** [comment]
I am happy to help, I can work in most areas and help with organization. For issue import this may help deal with the issues in a nicer way. https://github.com/IQAndreas/github-issues-import

**Comment by cleaverm** [comment]
I'd like to contribute. I work with Angular, Django and Docker, although my focus is mostly on the front-end side of things.

I'm new to the codebase but would put my hand up for bugfixing, testing or just an extra set of eyes on a PR.

**Comment by kpj** [comment]
Another happy paperless-ng user here, I could help with Python, Docker and Github Actions stuff if needed.

**Comment by azapater** [comment]
I'm also willing to help. Although my background is more PHP, Vue and Pascal, I wouldn't mind learning Django & Angular. Also, I can help with translations to Spanish if it's needed.

**Comment by qcasey** [comment]
> For issue import this may help deal with the issues in a nicer way. https://github.com/IQAndreas/github-issues-import

@sytone Thanks for the link, added to the Task. I've had a `?` on Migrate Issues because I'm not sure if everyone is agreed with importing lots of un-contextualized and likely stale issues. Definitely something to discuss.

To everyone else so far: **thank you** for volunteering, I have added you to the list :smiley:

**Comment by a17t** [comment]
@qcasey thanks for bringing this forward and for the efforts!

Enjoy Superbowl!

**Comment by larena1** [comment]
@qcasey what about you as head of the organization? You seem pretty invested in the future of paperless anyway and probably also have the skills and knowledge it would take.

**Comment by alexander-bauer** [comment]
I'm also very interested in the continued development of this project. I'm a relatively new user, but am running a Kubernetes-backed instance at home, and have a professional background in platform and software engineering. My time is in relatively short supply, but I would be glad to contribute with as much of it as I'm able.

**Comment by shamoon** [comment]
Ok guys & gals, Im onboard. I dont have a ton of time to dedicate right now to new stuff but would be good to get current PRs merged, issues sorted, etc. I have small amount of Python experience, dont know much about packaging stuf. Im def more front-end.

Im a bit sad its come to this but mostly I hope all's OK for Jonas. I think whenever he does come back up for air he'll be happy to see the community built up around the project.

**Comment by skorvek** [comment]
Willing to help in any way possible. Not a programmer (work mostly on the sysadmin end), but use paperless for home and small-business uses.  This project is essential to my life- sanity, keeping the office floor visible, and keeping all businesses straight. 

I run a cluster of servers at home, and can easily spin up development VMs and docker stacks as needed to alpha/beta test builds on a non-production copy of my files. Run a ton of open-source applications and am constantly trying to integrate them in a better/easier workflow.

Also willing to help in any way possible with triaging tickets and ensuring they stay organized, documentation, and the like.

**Comment by FrankStrieter** [comment]
I'll invite all of you who want to join and ask here for attendance so far. I am an enterprise Angular developer & consultant and I want to bring in my experience here in this Project. OSS contribution is new for me but I want to learn, so @qcasey if it is okay for you to be the head, go forward. I'll send the invitations to https://github.com/paperless-ngx/paperless-ng at least today.

**Comment by filcuk** [comment]
I'm happy to run a docker instance for testing and can translate (english <> czech) if that's of any value.
I can also bring this new repo to the attention of various users through forums to help gain traction.

**Comment by slankes** [comment]
Count me in as well. I would like to do ticket triaging and would like to work on automated testing. This will then probably result in documentation fixes/updates as well.

**Comment by qcasey** [comment]
So much interest in keeping this project alive, that is great! @shamoon love to have you onboard. 

I'm just here to get people in the right places, if that means joining the org I'll do that. @FrankStrieter could you add myself @qcasey and @shamoon as owners? From there we can invite members and put people into the relevant teams based on their experience.

Thank you to everyone who has volunteered since yesterday! Once I'm settled in for the day I'll update the list of willing contributors.

**Comment by dblitt** [comment]
Thanks for everyone's work on this! I'm excited to see development resume (and contribute whenever I can).

One note about the new name: I think paperless-ngx is a fine name for the organization (at least for now), but should we also rename the repo itself to "paperless-ngx" to avoid confusion with Jonas' repo and clarify that this is a fork? Whenever the new project reaches a release state, we'll have to release the docker image under a new name anyway.

**Comment by yschroeder** [comment]
I'm interested as well. I just started to use paperless-ng. I am familiar with Python and Angular development, as well as CI testing (of Python, haven't done that for Angular yet). I don't know how much time I can devote to this project, but I would like to try.

**Comment by dblitt** [comment]
I'd be happy to help out with some packaging/backend python stuff. I'm not extremely familiar with the codebase, but I'm currently thinking about building a public link/sharing system to share hosted docs without others needing to have an account on the system, and I hope to have that done at some point for personal use.

**Comment by b1rdhous3** [comment]
WOW! So happy to see a revive here. I am just starting using paperless-ng and really miss a multi user feature. 
As I am not so familiar with python (just a bit), I am firm with CI/CD stuff and may be able to help if time permitts. But will monitor closely!

**Comment by jrester** [comment]
Running a personal instance of paperless-ng and was always wondering how the project is going to continue after this inactivity. Glad to see it there is a new movement keeping this project alive! I would be happy to help. I have a background in python software development, docker and infrastructure administration.

**Comment by ignoreigor** [comment]
First of all, congratulations on the decision to continue the work of the previous main developers and to honor Paperless and their achievements with Paperless.
I am curious to see how Paperless will grow up. And maybe I can have a look at some issues or lines of code, even though Python is not my main language, neither is English.
I think one of the most difficult and challenging tasks will be to determine the direction for Paperless to evolve. It turns out that user expectations run on in very different directions. With huge desires and expectations...
Jonas himself was quite clear about his intentions for Paperless in the [FAQs](https://paperless-ng.readthedocs.io/en/latest/faq.html). Some feature requests go far beyond that. 
But of course, I also have some features in mind that I would find useful for my daily paperless work.
I wish a lot of intuition and talent for this challenge!

**Comment by Timoms** [comment]
Howdy there! Thanks for the work you put into paperless - its an awesome project! Headed over to see this dedication to the project made me smile! 

If you need someone for Front/Backend or translation to DE - I'd love to help!
I am a Vue.JS developer with C# Backend but the knowledge in Python / Angular should be enough to create some features 😊.
I saw some LDAP feature request too - as an system engineer with access to ADFS / LDAP / AD I'd love to help with that too.

And a beta system running next to the main instance shouldn't be a problem too 😉!

**Comment by RaviKarrii** [comment]
I love the project. I have background in Python, Java and currently working as a release engineer as my day job. Let me know if I can help in anyway.

**Comment by smseidl** [comment]
@FrankStrieter Just caught up on the various "this project is dead threads'.  I'm glad to see the Paperless-NGX repo and the details above on how it would be split up with teams/etc.  I would love to help out currently as a tester, in any aspect.  I would likely contribute in other ways as well (I do middleware work for my job and am not afraid to jump into area's I don't know).

**Comment by scheralph** [comment]
Hi all, I would like to get involved in this project. I have used paperless and paperless-ng for some time and am interested in contributing here. I can help on the Backend side (Python) as well as with testing, Issue Triage, translation (EN-DE) and some project org if needed 😊
I am a Master's Computer Science Student with 3 years of Python experience from my studies as well as some personal projects and freelance work.

**Comment by sbrunner** [comment]
This repository isn't active anymore, you should have a look on the fork: https://github.com/paperless-ngx/paperless-ngx :-)

**Comment by thibaultmol** [comment]
> This repository isn't active anymore, you should have a look on the fork: https://github.com/paperless-ngx/paperless-ngx :-)

Shame that this isn't mention at the very top of the readme on this repo though

**Comment by slankes** [comment]
> Shame that this isn't mention at the very top of the readme on this repo though

Well yes - but the keeper of the keys is nowhere to be found so there is no way to put it there.
